all:
  vars:
    ansible_user: d3user # SSH пользователь, используемый Ansible
  hosts:
    vm1:
      ansible_host:
        10.1.5.5 # Адрес, используемый Ansible для подключения.
        # Должен быть доступен с контроллера
    vm2:
      ansible_host: 10.1.5.6
  children:
    part1:
    part2:
part1:
  hosts:
    vm1:
part2:
  hosts:
    vm2:
